language: cpp
dist: trusty
compiler:
- g++
os:
- linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

branches:
  only:
  - master

script:
  - cd src
  - mkdir bin
  - mkdir output
  - make
